### ISSUE TITLE
Create multiple migtable instances

### ISSUE THREAD

**Issue by roger-rainey** [GoogleCloudPlatform/deploymentmanager-samples#133] opened 2018-03-28 23:33 UTC
I am trying to deploy multiple bigtable instances but I am not sure of the format to do that. Here is what I have. I have also tried creating multiple entries under resources but that did not work either.
'''
imports:
  - path: bigtable.py

  - name: helper.py
    path: ../../../helper.py

resources:
  - name: permissions
    type: bigtable.py
    properties:
      instanceId: permissions
      instance:
        - name: dev-permissions
          displayName: dev-permissions
          type: PRODUCTION
        - name: qa-permissions
          displayName: qa-permissions
          type: PRODUCTION
        - name: stage-permissions
          displayName: stage-permissions
          type: PRODUCTION
      clusters:
        initial:
          location: us-central1
          defaultStorageType: SSD 
          serveNodes: 3           
      tables:
        arns:
          columnFamiles:
            features:
            parents:

**Comment by shuainie-google** [comment] 2018-03-29 01:09
@roger-rainey this python script doesn't support creating multiple bigtable instance out of box. You will need to refactor bigtable.py and add an outer layer loop to read a list of instance name from the config property you defined and construct the config block for each instance

**Comment by shuainie-google** [comment] 2018-03-30 15:49
Closing this since this is not a bug in template

**Closed by shuainie-google** 2018-03-30 15:49 UTC
