### ISSUE TITLE
project_creation folder management

### ISSUE THREAD

**Issue by davidebelloni** [GoogleCloudPlatform/deploymentmanager-samples#36] opened 2017-09-14 14:28 UTC
Hi,
I know that cloudresourcemanager.v1.project API doesn't support folders and so I've to move the project by hand from org to folder, but after that I can't update deployment (for example to change iam bindings on project or create service account) because I've the following error:

```
ERROR: (gcloud.deployment-manager.deployments.update) Error in Operation [operation-1505398303589-55926db218288-6c7b630d-56dd0f1d]: errors:
- code: RESOURCE_ERROR
  location: /deployments/<deployment>/resources/project
  message: '{"ResourceType":"cloudresourcemanager.v1.project","ResourceErrorCode":"403","ResourceErrorMessage":{"code":403,"message":"User
    is not authorized.","status":"PERMISSION_DENIED","details":[{"@type":"type.googleapis.com/google.rpc.ResourceInfo","resourceType":"FOLDER","resourceName":"FolderId{toLong=<folderid>,
    getResourceType=FOLDER}"}],"statusMessage":"Forbidden","requestPath":"https://cloudresourcemanager.googleapis.com/v1/projects/<project>","httpMethod":"PUT"}}'

```

Thanks

**Comment by adamharwayne** [comment] 2017-09-14 17:56
I think what is happening is that when you are updating the deployment, it is attempting to move the project back under the organization, out of the folder. You can check by looking at the project resource's update.finalProperties. If they have parent.type equal to organization, then it is attempting the move. 

The 403 is because the service account DM is running under does not have permission to move the project. If you want the move, then give the service account the permission to move the project.

If you don't want the project to move, then a work around is to modify project.py to emit the parent property of your folder (as the template does not currently support folders).

So:


        'parent': {
              'type': 'organization',
              'id': context.properties['organization-id']
          }

Would become:


        'parent': {
              'type': 'folder',
              'id': context.properties['folder-id'] # Or hard code the folder-id here. If not hard coded, update project.py.schema to make organization-id optional.
          }

**Comment by davidebelloni** [comment] 2017-09-15 06:42
Hi, thank for the quick reply.
I confirm what you say, but at the same time I advice to improve documentation (overall): 

- the folder type is not documented (doc. says "The only supported parent type is "organization")
- when and how to use "type: gcp-types/.." and "action: gcp-types/..."
- which of the methods of the above APIs are valid with DM
- some types are not listed (example deploymentmanager.v2.virtual.enableService)

Thanks

**Comment by jaivasanth-google** [comment] 2017-09-28 20:58
Thanks for your feedback Davide. I have just committed a change to the project creation template that adds parent-folder-id as another supported option. 
The actions feature is still in alpha and we plan to documentation when we launch it to GA.
deploymentmanager.v2.virtual.enableService was intended to be a stop gap for us to support enabling apis till we launch actions. We will be moving over to using actions instead of virtual types.

**Closed** 2017-09-28 20:59 UTC
