### ISSUE TITLE
Remove default CloudSQL root user

### ISSUE THREAD

**Issue by davidebelloni** [GoogleCloudPlatform/deploymentmanager-samples#49] opened 2017-10-20 15:30 UTC
Hi,
I'm trying without success to remove the default 'root@%' CloudSQL user with DM.

Is there a method to call "sqladmin.user.delete" on 'sqladmin-v1beta4' provider?

Thanks

**Comment by krwenholz** [comment] 2017-10-30 19:31
Hi Davide,

This is probably a good use of DM Actions (public documentation coming later this quarter). I think something like the following would delete the user when you create the database. You may need to add a dependsOn clause to get things working consistently. I haven't had a chance to test this today, but it should get you going.

```
- name: delete-root
  action: gcp-types/sqladmin-v1beta4:sqladmin.users.delete
  metadata:
    runtimePolicy:
    - CREATE
  properties:
    project: your-project
    instance: your-instance-name
    host: your-host-name
    name: root
```

Now, that depends on Cloud SQL letting you delete the user through their API, which they may not allow for root.

Let us know if there's anything we can do to help and feel free to reopen this issue.

**Comment by davidebelloni** [comment] 2017-10-31 08:00
Hi @krwenholz ,
I've tried what you say but in jinja values can't begin with %, and in this case "host" should be %:

```
ERROR: (gcloud.deployment-manager.deployments.update) Error in Operation [operation-1509436639964-55cd31abc6b60-c83f63d1-66ad4bc7]: errors:
- code: MANIFEST_EXPANSION_USER_ERROR
  message: |
    Manifest expansion encountered the following errors: while scanning for the next token
    found character '%' that cannot start any token
      in "<unicode string>", line 58, column 11:
            host: %
                  ^ Resource: config
```

Instead, if I try to convert the template in python I've the following error:
```
ERROR: (gcloud.deployment-manager.deployments.update) Error in Operation [operation-1509436126072-55cd2fc1b0cc0-7db86074-efe2e1d1]: errors:
- code: CONDITION_NOT_MET
  message: |-
    404 Not Found
    {
      "code" : 404,
      "errors" : [ {
        "domain" : "global",
        "message" : "The object 'projects/gcp-types/global/typeProviders/sqladmin-v1beta4' is not found.",
        "reason" : "notFound",
        "debugInfo" : "com.google.api.server.core.Fault: ImmutableErrorDefinition{base=NOT_FOUND, category=USER_ERROR, cause=null, debugInfo=null, domain=global, extendedHelp=null, httpHeaders={}, httpStatus=notFound, internalReason=Reason{arguments={}, cause=null, code=bigcluster.BigClusterErrorDomain.RESOURCE_NOT_FOUND, createdByBackend=true, debugMessage=null, errorProtoCode=RESOURCE_NOT_FOUND, errorProtoDomain=bigcluster.BigClusterErrorDomain, filteredMessage=null, location=null, message=The resource 'projects/gcp-types/global/typeProviders/sqladmin-v1beta4' was not found, unnamedArguments=[projects/gcp-types/global/typeProviders/sqladmin-v1beta4]}, location=null, message=The object 'projects/gcp-types/global/typeProviders/sqladmin-v1beta4' is not found., reason=notFound, rpcCode=404} The object 'projects/gcp-types/global/typeProviders/sqladmin-v1beta4' is not found.
        at com.google.api.server.core.ErrorCollector.toFault(ErrorCollector.java:54)
        at com.google.api.server.rest.adapter.rosy.RosyErrorConverter.toFault(RosyErrorConverter.java:67)
        at com.google.api.server.rest.adapter.rosy.RosyHandler$2.call(RosyHandler.java:258)
        at com.google.api.server.rest.adapter.rosy.RosyHandler$2.call(RosyHandler.java:238)
        at com.google.api.server.core.util.CallableFuture.run(CallableFuture.java:62)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:403)
        at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1019)
        at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:870)
        at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:694)
        at com.google.api.server.core.util.CallableFuture.run(CallableFuture.java:62)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:403)
        at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1019)
        at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:870)
        at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:694)
        at com.google.api.server.core.util.CallableFuture.run(CallableFuture.java:62)
        at com.google.api.server.thread.ThreadTrackers$ThreadTrackingRunnable.run(ThreadTrackers.java:126)
        at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:454)
        at com.google.api.server.server.CommonModule$ContextCarryingExecutorService$1.runInContext(CommonModule.java:841)
        at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:461)
        at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:297)
        at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:320)
        at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:312)
        at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:458)
        at com.google.gse.internal.DispatchQueueImpl$WorkerThread.run(DispatchQueueImpl.java:387)"
      } ],
      "message" : "The object 'projects/gcp-types/global/typeProviders/sqladmin-v1beta4' is not found."
    }
```

P.S: what is the meaning of the following section (not documented):
```
  metadata:
    runtimePolicy:
    - CREATE
```

**Comment by davidebelloni** [comment] 2017-10-31 08:02
Hi,
I can't reopen this issue because: "you cannot re-open your own issues if a repo collaborator closed them"

**Comment by davidebelloni** [comment] 2017-10-31 08:02
Hi,
I can't reopen this issue because: "you cannot re-open your own issues if a repo collaborator closed them"

**Comment by krwenholz** [comment] 2017-10-31 18:09
Sorry about that Davide. It looks like our docs were behind reality. I'll get that fixed in the next day or two and report back here.

**Comment by krwenholz** [comment] 2017-10-31 18:13
Regarding that metadata section, that says to run the action when the deployment is created. There are some other options but they aren't necessary for your use case (I think). Documentation for this feature won't be released until the end of the quarter.

**Comment by krwenholz** [comment] 2017-11-07 17:21
I got the sample up but forgot to comment back here. Sorry about that. You can find a sample of creating a database and removing the root user [here](https://github.com/GoogleCloudPlatform/deploymentmanager-samples/tree/master/examples/v2/sqladmin).

Happy Tuesday.

**Comment by davidebelloni** [comment] 2017-11-09 08:59
Hi @krwenholz ,
I've tried the sample on my database but I've the following error:

```
The fingerprint of the deployment is E2eOnmGR6p1OYP0Ox4EZxA==
Waiting for update [operation-1510217280311-55d88dc86ced8-d165781c-e1d26bdb]...failed.                                                                                                                                                                                                                                    
ERROR: (gcloud.deployment-manager.deployments.update) Error in Operation [operation-1510217280311-55d88dc86ced8-d165781c-e1d26bdb]: errors:
- code: RESOURCE_ERROR
  location: /deployments/resources/resources/db-test-mysql-def-root
  message: '{"ResourceType":"gcp-types/sqladmin-v1beta4:sql.users.delete","ResourceErrorCode":"INTERNAL_ERROR","ResourceErrorMessage":""}'
```

In Cloud Logging I've:

```
insertId: 55D88DEFA3809.AE91682.2106CD10
logName: projects/my-project/logs/cloudaudit.googleapis.com%2Factivity
operation:
  id: operation-1510217280311-55d88dc86ced8-d165781c-e1d26bdb
  last: true
  producer: deploymentmanager.googleapis.com
protoPayload:
  '@type': type.googleapis.com/google.cloud.audit.AuditLog
  authenticationInfo:
    principalEmail: my_account@my_domain
  methodName: v2.deploymentmanager.deployments.update
  requestMetadata:
    callerIp: X.X.X.X
    callerSuppliedUserAgent: google-cloud-sdk x_Tw5K8nnjoRAqULM9PFAC2b gcloud/178.0.0
      command/gcloud.deployment-manager.deployments.update invocation-id/b780047ce8f046409daa3d3bc6e84b1d
      environment/None environment-version/None interactive/True python/2.7.13 (Macintosh;
      Intel Mac OS X 16.7.0),gzip(gfe)
  resourceName: projects/my-project/global/deployments/resources
  serviceName: deploymentmanager.googleapis.com
  status:
    message: BAD_REQUEST
receiveTimestamp: '2017-11-09T08:48:42.313532288Z'
resource:
  labels:
    name: resources
    project_id: my-project
  type: deployment
severity: NOTICE
timestamp: '2017-11-09T08:48:41.315Z'
```

My DB has the default account as 'root'@'%', why do you try to delete the account 'root'@'localhost'?

Thanks

**Comment by krwenholz** [comment] 2017-11-09 16:04
Hi Davide,

Did deleting 'root'@'%' work for you? In my deployment I created, I ended up with 'root'@'localhost' being the default account. If I look at the users list in the console I see "User name" root and "Host name" localhost listed along with anonymous. You see a "%" in the "Host name" column? 

This may be due to a change in the cloud SQL backend or because I'm internal, but I wouldn't really know (the error is from sqladmin not DM). I'm opening an internal bug with that team to get the real error message and will report back here once I have that.

Can you provide the config you used? (Scrub out any personal details though.) That will help figure out exactly what request was sent.

Thanks.

**Comment by davidebelloni** [comment] 2017-11-10 10:28
Hi @krwenholz ,
yes in the "Host name" column on CloudSQL Console I see "% (any host)".

The config about the cloud sql resources are:

```
- name: db-test-mysql
  type: sqladmin.v1beta4.instance
  properties:
    backendType: SECOND_GEN
    databaseVersion: MYSQL_5_6
    failoverReplica:
      available: false
    instanceType: CLOUD_SQL_INSTANCE
    name: db-test-mysql
    region: australia-southeast1
    settings:
      activationPolicy: ALWAYS
      backupConfiguration:
        binaryLogEnabled: true
        enabled: true
        startTime: '13:00'
      dataDiskSizeGb: 10
      dataDiskType: PD_SSD
      ipConfiguration:
        authorizedNetworks: []
        ipv4Enabled: true
        requireSsl: true
      locationPreference:
        zone: australia-southeast1-a
      maintenanceWindow:
        day: 2
        hour: 17
      storageAutoResize: true
      storageAutoResizeLimit: 100
      tier: db-g1-small
      userLabels:
        hex: 7ce691c82ba3

- name: db-test-mysql-def-root
  action: gcp-types/sqladmin-v1beta4:sql.users.delete
  properties:
    host: localhost
    instance: $(ref.db-test-mysql.name)
    name: root
    project: <project_id>
  metadata:
    runtimePolicy:
    - CREATE
    dependsOn:
    - db-test-mysql
```

I've set "host" to "locahost" as you said (also because I can't set it to "%" in yaml)

Thanks

**Comment by krwenholz** [comment] 2017-11-10 16:52
Did setting host to localhost work? Did you put the plain % in or did you try wrapping it in quotes? Can you clarify what has or hasn't worked and if you get different error messages? I don't see anything else wrong with your deployment, so this is just a matter of finding the correct value for host.

I haven't heard back from the Cloud SQL team, but their SLO on this level of issue suggests we might not hear anything for another 5 business days.

**Comment by davidebelloni** [comment] 2017-11-13 09:36
Nope,
setting "localhost" doesn't work (because I don't have this user), setting '%' or "%" doesn't work because yaml doesn't permit the char % in value. I think you can reply the issue creating a user 'test'@'%' e trying to remove it.

Thanks

**Comment by krwenholz** [comment] 2017-11-13 17:20
Hi Davide,

I managed to delete root@% using the following example

```
resources:
- name: quuxinstance2
  type: gcp-types/sqladmin-v1beta4:instances
  properties:
    settings:
      tier: D1
- name: bazzdb2
  type: gcp-types/sqladmin-v1beta4:databases
  metadata:
    dependsOn:
    - quuxinstance2
  properties:
    name: bazzdb2
    instance: quuxinstance2
    charset: utf8
- name: db-test-mysql-def-root-1
  action: gcp-types/sqladmin-v1beta4:sql.users.delete
  properties:
    host: "%"
    instance: quuxinstance2
    name: root
    project: test-wenholz
  metadata:
    runtimePolicy:
    - CREATE
    dependsOn:
    - bazzdb2
```

Wrapping the % in quotes was necessary to get the yaml parsing correctly. At the moment, updating actions (e.g. changing the value of host) is broken so you'll need to create a new action name or recreate the deployment. This should be fixed in our next release.

Let me know if using "%" works or you still have trouble (paste the exact error message and scrubbed if this happens).

Happy Monday,

Kyle

**Comment by davidebelloni** [comment] 2017-11-14 15:04
Hi @krwenholz ,
using "%" now it works. I would bet that I have already done this!

Thank you for the support

**Comment by krwenholz** [comment] 2017-11-14 16:30
I'm glad it's working now! Let us know if there's anything else we can help with. The internal team is working to fix the INTERNAL_ERROR so future users aren't confused.

**Comment by davidebelloni** [comment] 2017-11-17 15:39
Hi @krwenholz 
I've deleted the deployment (with delete-policy ABANDON) e recreated.
I can't understand why I've:

```
gcloud beta deployment-manager deployments update resources --project "$DMPROJECT" --config resources.yaml --create-policy=acquire
The fingerprint of the deployment is xjc-V4pjsWAdoQCaFjDIaA==
Waiting for update [operation-1510932914140-55e2f7ba07362-bed47382-1966d3f8]...failed.                                                                                                                                                                                                                                    
ERROR: (gcloud.beta.deployment-manager.deployments.update) Error in Operation [operation-1510932914140-55e2f7ba07362-bed47382-1966d3f8]: errors:
- code: INTERNAL_ERROR
  message: 'Code: ''-6601267566415772341'''

```
with an update command: 

`gcloud beta deployment-manager deployments update resources --project "$DMPROJECT" --config resources.yaml --create-policy=acquire
`
and this conf

```
- name: {{ DEFROOT }}
  action: gcp-types/sqladmin-v1beta4:sql.users.delete
  properties:
    instance: $(ref.{{ SQL }}.name)
    name: root
    host: "%"
    project: {{ env['project'] }}
  metadata:
    runtimePolicy:
    - CREATE

```

Thanks

**Comment by krwenholz** [comment] 2017-11-17 17:53
Hi Davide,

This looks like a bug on our end. I have opened an internal bug to track it. The problem is with the action and create-policy=acquire, so you should be able to recreate and use that same update command if you leave out the action. Then add the action back in and update without create-policy=acquire.

We should have a permanent fix for this out by the end of the year.

Sorry for the trouble.

**Comment by davidebelloni** [comment] 2018-01-23 07:55
Hi @krwenholz ,
is internal bug resolved by now?

Thanks!

**Comment by krwenholz** [comment] 2018-01-23 16:56
Hi Davide,

I've been out on a long leave since December, so I'm not sure. I'll reopen this (sorry I forgot to keep it open) so it gets a look from one of my coworkers who can answer your question.

On-call who gets assigned this bug, please confirm whether or not actions work with create-policy=acquire. There should be a bug opened for it around the time of my last comment.

Thanks.

**Comment by katyp** [comment] 2018-01-24 18:16
Hi you two, it looks like actions should work with acquire intent now. Actually, Kyle himself is the one who fixed it in November. Davide, can you confirm that it is working for you now?

**Comment by katyp** [comment] 2018-01-29 17:28
Closing. Please re-open if necessary.

**Closed** 2018-01-29 17:28 UTC
