### ISSUE TITLE
ResourceError Code 400 when updating GKE addOnsConfig

### ISSUE THREAD

**Issue by jiang-wei** [GoogleCloudPlatform/deploymentmanager-samples#147] opened 2018-04-10 18:45 UTC
When updading a GKE cluster previously created with DM, get the error.

I've enabled the k8s dashboard manually in the GKE web console, and I'd like to update the DM configuration and I ran the updating command.

Here's the error message:

```json
{"ResourceType":"container.v1.cluster","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"addons_config must specify values for http_load_balancing and/or horizontal_pod_autoscaling.","status":"INVALID_ARGUMENT","statusMessage":"Bad Request","requestPath":"https://container.googleapis.com/v1/projects/............./clusters/gke-cluster/addons", "httpMethod":"POST"}}
```

the expanded config looks like:
```
resources:
- name: gke-cluster
  properties:
    cluster:
      addonsConfig:
        horizontalPodAutoscaling:
          disabled: false
        httpLoadBalancing:
          disabled: false
        kubernetesDashboard:
          disabled: false                  # used to be true when I previously created the gke cluster
      initialClusterVersion: 1.8.9-gke.1
      legacyAbac:
        enabled: true
      name: gke-cluster
      nodePools:
      - autoscaling:
          enabled: true
          maxNodeCount: 15
          minNodeCount: 1
        config:
          diskSizeGb: 100
          imageType: cos
          oauthScopes:
          - https://www.googleapis.com/auth/compute
          - https://www.googleapis.com/auth/devstorage.read_only
          - https://www.googleapis.com/auth/logging.write
          - https://www.googleapis.com/auth/monitoring
        initialNodeCount: 2
        management:
          autoRepair: false
          autoUpgrade: false
        name: default-pool
    zone: us-central1-c
  type: container.v1.cluster
```

The addonsConfig is there.

**Comment by jiang-wei** [comment] 2018-04-10 20:42
operation id: operation-1523384967799-56982b3dca0d8-e3bda9ee-1e2da31d

but why need to disable one of hpa, dashboard or load balancing?

**Comment by vagababov** [comment] 2018-04-16 19:25
This seems like a bug in DM, but I have no ETA for it.

**Comment by shuainie-google** [comment] 2018-04-17 22:41
For some reason, GKE API require at least one of the "httpLoadBalancing" and "horizontalPodAutoscaling" field to be set in the request body when you are updating "kubernetesDashboard" in "addonsConfig". This seems weird since I don't see direct dependencies between those addons. I have started an internal thread with GKE team on this matter and will update here when I heard back from them.

In your case, since "httpLoadBalancing" and "horizontalPodAutoscaling" doesn't change from existing value, these two fields will be removed from the update quest sent by DM. This is expected behavior from DM.
One workaround is to do following 2 updates to make sure the second update request keeps "httpLoadBalancing" field

update request1:
  httpLoadBalancing:
    disabled: true

update request2:
  httpLoadBalancing:
    disabled: false
  kubernetesDashboard:
    disabled: false

**Comment by shuainie-google** [comment] 2018-04-23 17:48
Closing this here since this is an API issue and we have internal bug tracking this with GKE team.

**Closed by shuainie-google** 2018-04-23 17:48 UTC
